### ISSUE TITLE
yolov5 postprocess on triton server (output shape structure)

### ISSUE THREAD

**Issue by Amanda-Barbara** [svtdanny/train-serve-yolov5#1]
Hi, can you share the postprocess method of yolov5 serises model on triton server, I only see the return value res' shape is (1,25200,13), how can I obtain the bounding box , confidence an class id infomation ? thanks .

**Comment by svtdanny** [comment]
Hello, @Amanda-Barbara !

1 - batch size
25200 - number of predictions per image (really, I forgot to apply NMS on result to reduce this number to meaningful value. You can take this function "non_max_suppression" from https://github.com/ultralytics/yolov5/blob/master/utils/general.py )
13 - you can see structure on the image (in this case I had 8 classes):

![Untitled Diagram-3](https://user-images.githubusercontent.com/66482706/129236303-485d43b5-f20b-442b-bc61-ea82591cf2ca.png)

**Comment by svtdanny** [comment]
Sorry, accidentally closed the issue. If I didn't answer your question, tweak me please

**Comment by Amanda-Barbara** [comment]
@svtdanny I have add the code of general.py  according  https://github.com/ultralytics/yolov5/blob/master/utils/general.py
and the finally result like this:
tensor([[2.70752e+02, 2.85657e+02, 3.65133e+02, 3.71977e+02, 5.89501e-01, 3.00000e+00],
        [1.96444e+02, 1.37198e+02, 2.29804e+02, 1.61766e+02, 3.68322e-01, 0.00000e+00],
        [4.40706e+02, 3.22659e+02, 4.79106e+02, 3.59334e+02, 2.80714e-01, 1.00000e+00]])
when I draw the bounding box on the images, the detected bounding box is not right, How can I fix it ? thanks .

**Comment by svtdanny** [comment]
@Amanda-Barbara basically, I don't know. Where are a lot of missing content. 
What data and model did you used? 
If both mine then it could be even bad sample
For example where was mislabels on used fishes dataset (occasionally penguins were called "Jellyfish"). So the same was on the validation/test data

But I think provided output is really reasonable, so it's seems not to be the problem with the code

**Comment by Amanda-Barbara** [comment]
@svtdanny I used your trained onnx model deployed on triton server, the model and my draw bbox code like this:
```c++
client = RemoteClient(
    url = 'localhost:6001',
    model_name = 'yolo5m_base',
    img_size = (640, 640)
)
``` 
```c++
for j, bbox in enumerate(output[0]):
            cv2.rectangle(img, (int(bbox[0]), int(bbox[1])), (int(bbox[2]), int(bbox[3])), color, 3, cv2.LINE_AA)
```       
the second image detected result like this:
![2021-08-17 09-53-37 创建的截图](https://user-images.githubusercontent.com/38062165/129651198-7163b840-7290-4ca4-871f-22fdef4e4a7d.png)

1
tensor([128.02647, 298.46356, 435.55212, 441.80328,   0.58690,   2.00000])
and I draw the bbox result on the picture like this:
![2021-08-17 09-45-08 创建的截图](https://user-images.githubusercontent.com/38062165/129650601-9a740796-fc50-437f-a6ba-42dad8d3b619.png)
I think the detected result is right, the coordinates may be not corresponding to the image, but I according the x1y1x2y2 to draw it, How to solve it ? thanks .

**Comment by svtdanny** [comment]
Hi, @Amanda-Barbara!
Seems to be some bug in code (with size transforming). I'm not sure on which side is it
I tested it's correctness with repository script. All were ok

Then I just transformed model to ONNX then to TensorRT (inside triton loader)
